export const SELECT_ALL_CART_GOODS = 'SELECT_ALL_CART_GOODS';
export const FETCH_CART_DATA_SUCCESS = 'FETCH_CART_DATA_SUCCESS';
export const UPDATE_CART_GOODS_QUANTITY = 'UPDATE_CART_GOODS_QUANTITY';
export const UPDATE_CART_CHECKED_SHOP = 'UPDATE_CART_CHECKED_SHOP';
export const UPDATE_CART_CHECKED_GOODS = 'UPDATE_CART_CHECKED_GOODS';
export const CLEAR_CART_CHECKED_DATA = 'CLEAR_CART_CHECKED_DATA';
export const REMOVE_CART_GOODS = 'REMOVE_CART_GOODS';
// 食堂迷你购物车
export const UPDATE_CANTEEN_CART_GOODS_QUANTITY =
  'UPDATE_CANTEEN_CART_GOODS_QUANTITY';
export const UPDATE_CANTEEN_CART_GOODS = 'UPDATE_CANTEEN_CART_GOODS';
export const CLEAR_CANTEEN_CART_GOODS = 'CLEAR_CANTEEN_CART_GOODS';
export const REMOVE_CANTEEN_CART_GOODS = 'REMOVE_CANTEEN_CART_GOODS';
