export const SET_ORDER_LIST_REFRESH = 'SET_ORDER_LIST_REFRESH';
export const SET_ORDER_LIST_REFRESH_IMMEDIATE = 'SET_ORDER_LIST_REFRESH_IMMEDIATE';
export const RESET_ORDER_LIST_REFRESH = 'RESET_ORDER_LIST_REFRESH';

export const SET_ORDER_DETAIL_REFRESH = 'SET_ORDER_DETAIL_REFRESH';
export const SET_ORDER_DETAIL_REFRESH_IMMEDIATE = 'SET_ORDER_DETAIL_REFRESH_IMMEDIATE';
export const RESET_ORDER_DETAIL_REFRESH = 'RESET_ORDER_DETAIL_REFRESH';

